title = "tty2pico Example Configuration"

[tty2pico]
backgroundColor = 0
tftWidth = 240
tftHeight = 240
tftRotation = 0
disableSD = false
enableOverclock = true
waitForSerial = false
imagePath = "/logos/"
startupCommand = "CMDBYE"
startupDelay = 5000
startupImage = "/logos/pattern.loop.gif"
slideshowFolder = "/logos/"
slideshowDelay = 5000
ttyBaudRate = 115200