title = "tty2pico Example Configuration"

[tty2pico]
backgroundColor = 0
tftWidth = 240
tftHeight = 240
tftRotation = 0
overclockMode = 1
waitForSerial = false
imagePath = "/logos/"
startupCommand = "CMDBYE"
startupDelay = 5000
startupImage = "/logos/pattern.loop.gif"
slideshowDelay = 5000
ttyBaudRate = 115200