title = "tty2pico RoundyPi MaxOC Configuration"

[tty2pico]
backgroundColor = 0
# tftWidth = 240
# tftHeight = 240
# tftRotation = 2
overclockMode = 255
overclockSD = true
startupCommand = ""
startupDelay = 5000
startupImage = ""
slideshowDelay = 2000
uncapFramerate = false