name: PlatformIO Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pio platform install raspberrypi
    - name: Run PlatformIO
      run: |
        cd arduino/tty2pico
        pio run -e Pico-GC9A01
        mv .pio/build/Pico-GC9A01/firmware.uf2 .pio/build/Pico-GC9A01/tty2pico-Pico-GC9A01_${{ steps.tagName.outputs.tag }}.uf2
        pio run -e Pico16MB-GC9A01
        mv .pio/build/Pico16MB-GC9A01/firmware.uf2 .pio/build/Pico16MB-GC9A01/tty2pico-Pico16MB-GC9A01_${{ steps.tagName.outputs.tag }}.uf2
        pio run -e RoundyPi
        mv .pio/build/RoundyPi/firmware.uf2 .pio/build/RoundyPi/tty2pico-RoundyPi_${{ steps.tagName.outputs.tag }}.uf2
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          .pio/build/Pico-GC9A01/tty2pico-Pico-GC9A01_${{ steps.tagName.outputs.tag }}.uf2
          .pio/build/Pico16MB-GC9A01/tty2pico-Pico16MB-GC9A01_${{ steps.tagName.outputs.tag }}.uf2
          .pio/build/RoundyPi/tty2pico-RoundyPi_${{ steps.tagName.outputs.tag }}.uf2
